language: python
python:
- 3.7
- 3.6
- 3.5
dist: xenial
sudo: true
install:
- pip install -U tox-travis flake8
- pip install -r requirements_dev.txt
script:
- flake8 pydnameth, tests
- tox
- coverage run --source pydnameth setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: AaronBlare
  password:
    secure: U55gReMQZoxp1kNJ0Ut8hjXdwmSsmcC3x9So47U9IIUUQMXEBthgn8JGBaFA1cvzGW3h6DLk9bR4Me8BYOBdC08ujAOh1451ckG1q3DLbBP1zxsy2pUFXGSQXnLxZuHj6pwroywKWIL+8r/FPNYAWadJXy/jbLVtyGwagbFKYzugd1RYntQO/8OXzeqhuafP6NRegeMEWRA2d5I+NyM91kBBwEy3lvSTm4/h6w12AtjDNueI1H7fLi/kOxRmZpNr4FhX3XlPT9pQSsINNyDjASXfcPwIeBS9ytwaTMsnkKBjQ1Bor4ShFdWIV2bbUDliCmtpT9+9jAZRN1nylMS/g/shUV5DYLJ0QR4SZQg7IUwRqv9EgMnbT2y3jW0JoJoQJcKQWNHFnQwTvkbaY/WoDz7lWt9rW3r/YjPJzXLYGpLFMtxrTtg83QHdobvGEgYl8PD89OMpL8ey36dTek6k0aYss5bBttqmVuDf1/u7m/TgOPJSMxBVzudMZ2KOvaaLj+cB48ldStkx1PLxqrkuHsJ1WF5dA60dUP6abbypR7b4tzVfvzWhEE9Txdpcrkgu4tiqmDq9G3G1a7YaERTkzWAIBQLUPH+GOqUDgejrUqGs47NN1igXPgrDdbIpx3XNtjfrtCoKST7ypeR6KY7wyZB+3LbBLBPWdZidexI2CEc=
  on:
    tags: true
    repo: AaronBlare/pydnameth
    python: 3.6
