matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:

  matrix:
    - TOXENV: 'py35'
      MINICONDA: "C:\\Miniconda35-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.5"
      
    - TOXENV: 'py36'
      MINICONDA: "C:\\Miniconda36-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.6"
      
    - TOXENV: 'py37'
      MINICONDA: "C:\\Miniconda37-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.7"

# all our python builds have to happen in tests_script...
build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
    # set up environment
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
    - conda config --set always_yes yes
    - conda update -q conda
    - conda create -n test-env python=%PYTHON_VERSION%
    - activate test-env
    - conda install shapely --channel=conda-forge
    - python.exe -m pip install --upgrade pip
    - python.exe -m pip install -U flake8
    - python.exe -m pip install -r requirements_dev.txt"

test_script:
    - python.exe -m flake8 pydnameth, tests
    - python.exe -m tox
